encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.wiki, name="wiki"),
    path("search/", views.search, name="search"),
    path("new/", views.newpage, name="newpage"),
    path("wiki/<str:entry>/edit/", views.edit, name="edit"),
    path("random/", views.randompage, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from http.client import HTTPResponse
from django.shortcuts import render
import markdown2
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki(request, title):
    searchparam = title.capitalize()
    if title.lower() not in list(map(lambda t: t.lower(), util.list_entries())):
        messages.error(request, 'Error: No such url found.')
        return HttpResponseRedirect(reverse("wiki:index"))
    page = util.get_entry(title)
    displaytitle = '# ' + title.capitalize()
    page = markdown2.markdown(page)
    displaytitle = markdown2.markdown(displaytitle)
    return render(request, "encyclopedia/entry.html", {
        "page": page, "searchparam": searchparam, "title": title, "displaytitle": displaytitle
    })


def search(request):
    if request.method == "GET":
        param = request.GET.get('q')
        if util.get_entry(param):
            return HttpResponseRedirect(reverse("wiki:wiki", args=[param]))
    error = f'No search results found for "{param}", sorry!'
    searchentries = []
    entries = util.list_entries()
    for entry in entries:
        if param.lower() in entry.lower():
            searchentries.append(entry)
    return render(request, "encyclopedia/search.html", {
        "searchentries": searchentries, "param": param, "error": error
    })


def newpage(request):
    if request.method == "GET":
        return render(request, "encyclopedia/newpage.html")
    elif request.method == "POST":
        titledata = request.POST.get('titleform')
        contentdata = request.POST.get('contentform')
        link = f'<a href="/wiki/{titledata}">exists</a>'
        if titledata and contentdata:
            if titledata.lower() not in list(map(lambda t: t.lower(), util.list_entries())):
                util.save_entry(titledata, contentdata)
                messages.success(request, 'New entry added')
                return HttpResponseRedirect(reverse("wiki:index"))
        if link == '<a href="/wiki/">exists</a>':
            messages.error(
                request, f'Error: Did you forget to input a title?')
        else:
            messages.error(
                request, f'Error: Entry already {link}.')

        return HttpResponseRedirect(reverse("wiki:index"))


def edit(request, entry):
    if request.method == "GET":
        data = util.get_entry(entry)
        return render(request, "encyclopedia/edit.html", {"entry": entry, "data": data})
    elif request.method == "POST":
        edits = request.POST.get('contentform')
        if edits:
            util.save_entry(entry, edits)
            messages.success(request, 'Edited!')
            return HttpResponseRedirect(reverse("wiki:wiki", args=[entry]))
        messages.error(request, 'Error: Did you type anything?')
        return HttpResponseRedirect(reverse("wiki:wiki", args=[entry]))


def randompage(request):
    entries = util.list_entries()
    randomparam = random.choice(entries)
    return HttpResponseRedirect(reverse("wiki:wiki", args=[randomparam]))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>Editing {{ entry }}</h1>
<hr>
<form action="{% url 'wiki:edit' entry %}" method="post">
    {% csrf_token %}
    <h3> Content </h3>
    <textarea name="contentform" id="contentformid">{{ data }}</textarea>
    <div class="button-container">
        <button id="submitentry" type="submit" value="submit">Submit Entry</button>
    </div>
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - {{ searchparam }}
{% endblock %}

{% block body %}

<a href="{% url 'wiki:edit' title %}" class="btn btn-info" id="edit-button">Edit</a>

{{ displaytitle|safe }}

{{ page|safe }}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<header>
    <h1>All Pages</h1>
</header>

<ul>
    {% for entry in entries %}
    <li>
        <a href="/wiki/{{entry}}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">     
            <aside class="sidebar col-lg-2">
        {% if messages %}
            {% for message in messages %}
                {% if "success" in message.tags %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {% if "error" in message.tags %}
                    <div class="alert alert-danger" role="alert">
                        {{ message|safe }}
                    </div>                    
                {% endif %}    
            {% endfor %}
        {% endif %}               
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </aside>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

</body>

</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>Make a new entry</h1>
<div class="new-entry-container">
    <form action="{% url 'wiki:newpage' %}" method="post">
        {% csrf_token %}
        <textarea name="titleform" id="titletext" placeholder="Enter your title here"></textarea>
        <textarea name="contentform" placeholder="Enter your content here"></textarea>
        <div class="button-container">
            <button id="submitentry" type="submit">Submit Entry</button>
        </div>
    </form>

</div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

{% if searchentries|length != 0 %}
<h1>Search Results for: {{ param }}</h1>
{% else %}
<h1>{{ error }}</h1>

{% endif %}

<ul>
    {% for entry in searchentries %}
    <li>
        <a href="/wiki/{{entry}}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}